# Generated by Django 2.1.2 on 2018-12-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
